[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server/main.rs"


[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
