version: '3.8'
services:
  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 3s
      timeout: 10s
      retries: 3

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
      - ./diesel.toml:/app/diesel.toml:ro
      - ./docker.env:/app/.env:ro

volumes:
  pgdata:
